name: CI

on: [push, pull_request]

jobs:
  build:
    container: ubuntu:18.04
    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        apt update && apt install -y build-essential cmake valgrind
    - name: Build and run
      run: |
        mkdir build && cd build
        cmake ..
        make
